### ISSUE TITLE
Add example notebook for PostGIS

### ISSUE THREAD

**Issue by gbrener** [intake/intake-postgres#10]
An example notebook for PostGIS is currently in progress. This issue identifies the work item and will be closed once it is sufficiently completed to be checked in.

The demo notebook will start out as only showing Points data, with plans to be extended to demonstrate Lines, Polygons, and - time permitting - TINs.

**Comment by martindurant** [comment]
prefer to use https://github.com/informatics-lab/intake_geopandas/pull/2
