### ISSUE TITLE
Some postgres data types are not supported

### ISSUE THREAD

**Issue by LiuSikChung** [intake/intake-postgres#15]
Hi,

I am trying to use the intake plugin to query the postgres database

`import intake_postgres`
`df = intake_postgres(uri, sql_expr).read()`

Types of column: bigint, date, double precision, numeric, text, timestamp without time zone
And I got this error:

**File "iopro/postgresadapter/PostgresAdapter.pyx", line 489, in iopro.postgresadapter.PostgresAdapter.PostgresAdapter._get_default_types (postgresadapter/core/PostgresAdapter.c:5638)
RuntimeError: postgresql type 1700 not supported**

Then I try to create the table with only one column and one row, to see which type is not supported.

Results:
1. date
RuntimeError: postgresql type 1082 not supported

2. numeric
RuntimeError: postgresql type 1700 not supported

3. timestamp without time zone
RuntimeError: postgresql type 1114 not supported

4. text, double precision, bigint
no error

After some investigation on PostgresAdapter, there is a mapping for postgres data type to numpy data type. Then I passed field_name and field_types to PostgresAdapter by:
`sql_expr      = "SELECT * FROM testNumeric;"`
`pg_kwargs  = {"field_names":{0:'testNumericCol'},"field_types":{0:'i2'}}`
`df                = intake_postgres(uri, sql_expr, pg_kwargs)`

I still got the same error: **RuntimeError: postgresql type 1700 not supported**
Then I try to test it on bigint, it is working well
`sql_expr      = "SELECT * FROM testBigInt;"`
`pg_kwargs  = {"field_names":{0:'testBigIntCol'},"field_types":{0:'f2'}}`
`df                = intake_postgres(uri, sql_expr, pg_kwargs)`

   **testBigIntCol**
**0          1024.0**

The type change is actually working for bigint.
Is there anything I can do to let the PostgresAdapter know (from intake_postgres) the correct data type mapping in numpy

version:
intake          : 0.3.0
intake-postgres : 0.3.0
python          : 3.6.7

PostgresAdapter: https://github.com/ContinuumIO/PostgresAdapter/blob/master/postgresadapter/core/PostgresAdapter.pyx#L281

**Comment by martindurant** [comment]
I daresay that this belongs in the postgresadapter repo rather than here, but I'm not sure there's anyone currently working/maintaining it, so you may find no help unless you dig yourself, as you have been doing.

In the short term, though, you may want to consider using the intake-sql, which trades the transfer/parsing efficiency of this driver for flexibility and application to multiple database backends. In the case that downloading the results data is not the bottleneck for you, you may find a generally better experience with intake-sql.

**Comment by danielballan** [comment]
Since postgresdapater is not maintained, we are archiving this repo and encouraging all users to use [intake-sql](https://github.com/intake/intake-sql).
